export default {
  status: {
    id: 1,
    name: "status",
    title: "Статус",
    multi: true,
    multiAdd: false,
    width: "100%",
  },
  product_room_count: {
    id: 2,
    name: "product_room_count",
    title: "Количество комнат",
    multi: true,
    multiAdd: false,
    width: "100%",
  },
  sum_contract: {
    id: 3,
    name: "sum_contract",
    title: "Полная сумма в договоре",
    multi: false,
    width: "100%",
    checkbox: true,
  },
  handed_over: {
    id: 4,
    name: "handed_over",
    title: "Дом сдан",
    multi: false,
    width: "100%",
    checkbox: true,
  },
  mortgage: {
    id:5,
    name: "mortgage",
    title: "Ипотека",
    multi: false,
    width: "49%",
    checkbox: true,
  },
  repairment: {
    id: 6,
    name: "repairment",
    title: "Ремонт",
    multi: false,
    width: "49%",
    checkbox: true,
  },
  house_types: {
    id: 7,
    name: "house_types",
    title: "Вид объекта",
    multi: true,
    multiAdd: false,
    width: "100%",
  },
  house_floors: {
    id: 8,
    name: "house_floors",
    title: "Этажей в доме",
    multi: true,
    multiAdd: false,
    width: "100%",
  },
  house_construction: {
    id: 9,
    name: "house_construction",
    title: "Конструкция",
    multi: true,
    multiAdd: false,
    width: "100%",
  },
  house_communication: {
    id: 10,
    name: "house_communication",
    title: "Коммуникации",
    multi: true,
    multiAdd: true,
    width: "100%",
  },
  commercial_types: {
    id: 11,
    name: "commercial_types",
    title: "Вид объекта",
    multi: true,
    multiAdd: false,
    width: "100%",
  },
  status_lands: {
    id: 12,
    name: "status_lands",
    title: "Статус",
    multi: true,
    multiAdd: false,
    width: "100%",
  },
  parking_types: {
    id: 13,
    name: "parking_types",
    title: "Вид объекта",
    multi: true,
    multiAdd: false,
    width: "100%",
  },
  product_price: { id: 14,name: "product_price", title: "Цена, руб", multi: false },
  living_squares: {
    id: 15,
    name: "living_squares",
    title: "Площадь, м²",
    multi: false,
    width: "100%",
  },
  object_squares: {
    id: 16,
    name: "object_squares",
    title: "Площадь, м²",
    multi: false,
    width: "100%",
  },
  land_squares: {
    id: 17,
    name: "land_squares",
    title: "Площадь, сот",
    multi: false,
    width: "100%",
  },
  messages_calls: {
    id: 18,
    name: "messages_calls",
    title: "Звонки",
    multi: false,
    width: "100%",
    checkbox: true
  },
};
