import { createSlice } from "@reduxjs/toolkit";

const mockUser = {
  id: 296,
  user_name: "Андрей",
  phone: "+7 (937) 392-04-79",
  email: "andrey_vetrovoy@vk.com",
  user_group: {
    id: 5,
    name: "Супер Администратор",
    description: null,
  },
  date_registered: "2023-05-26T13:59:49.000Z",
  date_paid_to: null,
  paid: false,
  user_description: "FLATE.PRO - ресурс только для агентов. ",
  user_last_name: "Альбертович",
  favorites: [
    {
      id: 503,
      name: "ЖК Седьмое небо, 32 м², 1-комн., 2 этаж",
      slug: "zhk-sedmoe-nebo-32-m2-1-komn-2-etazh-503",
      date_created: "2023-06-05T11:28:48.000Z",
      date_edited: "2023-07-04T22:36:02.000Z",
      date_published: "2023-07-04T22:36:02.000Z",
      meta_title: null,
      meta_description: null,
      sort: null,
      section_relation: ["3"],
      user_id: 312,
      rc_link: 104,
      city_link: 5,
      area_link: 37,
      product_price: 7400000,
      living_squares: 32,
      land_squares: null,
      map_coordinates: null,
      product_description:
        "сдан, заселён,  счета разделены, всё центральное, газа нет, своя свободная парковка !!! и детская площадка:                         \r\nремонт, мебель, техника, супервид на море, балкон, Эксклюзив, ключи у меня. Обращайтесь ",
      status: "2",
      messages_calls: "0",
      product_placer: null,
      window_view: null,
      repairment: "0",
      cloud_links: null,
      comission: "Включена",
      comission_sum_terms: "200 тыс ваши",
      off_comission_value: null,
      mortgage: "1",
      stat_views: 47,
      published: 1,
      product_room_count: 0,
      sum_contract: "1",
      premium: "0",
      handed_over: 1,
      commercial_types: null,
      parking_types: null,
      object_squares: null,
      status_lands: null,
      house_types: null,
      house_floors: null,
      house_construction: null,
      flat_floors: 3,
      house_communication: null,
      date_banned: null,
      ban_note: null,
      edit_note: null,
      presentation: null,
      date_banned_to: null,
      date_paid: "2023-06-16T07:35:27.000Z",
      image: "/images/upload/2023-06-05/e511e510971b15907ab3f9005.jpg",
      youtube_video_link: null,
      building_link: null,
      pre_name: null,
      stat_views_preview: 840,
    },
    {
      id: 636,
      name: "Дом 195 м², 4 сотки",
      slug: "dom-195-m2-4-sotki-636",
      date_created: "2023-06-06T08:25:26.000Z",
      date_edited: "2023-07-06T17:26:02.000Z",
      date_published: "2023-07-06T17:26:02.000Z",
      meta_title: null,
      meta_description: null,
      sort: null,
      section_relation: ["4"],
      user_id: 323,
      rc_link: null,
      city_link: 5,
      area_link: 63,
      product_price: 45000000,
      living_squares: 195,
      land_squares: 4,
      map_coordinates: null,
      product_description:
        "Дом на Ереванской \r\nПредчистовая отделка. \r\n канализация - ЛОС.\r\nЗакрытая территория, парковка, бассейн с подогревом, ландшафтный дизайн. Шикарный вид на горы  и море \r\n",
      status: null,
      messages_calls: "0",
      product_placer: null,
      window_view: null,
      repairment: "1",
      cloud_links: null,
      comission: "Включена",
      comission_sum_terms: "по запросу",
      off_comission_value: null,
      mortgage: "0",
      stat_views: 40,
      published: 1,
      product_room_count: null,
      sum_contract: "1",
      premium: "0",
      handed_over: null,
      commercial_types: null,
      parking_types: null,
      object_squares: null,
      status_lands: null,
      house_types: 0,
      house_floors: 1,
      house_construction: 0,
      flat_floors: null,
      house_communication: [0, 1, 2],
      date_banned: null,
      ban_note: null,
      edit_note: null,
      presentation: null,
      date_banned_to: null,
      date_paid: "2023-06-16T07:33:10.000Z",
      image: "/images/upload/2023-06-06/9c5aa793d94d72fd11c13f604.jpg",
      youtube_video_link: null,
      building_link: null,
      pre_name: null,
      stat_views_preview: 1316,
    },
    {
      id: 691,
      name: "ЖК Огни Сочи, 58.4 м², 2-комн., 13 этаж",
      slug: "zhk-ogni-sochi-58-4-m2-2-komn-13-etazh-691",
      date_created: "2023-06-20T03:34:35.000Z",
      date_edited: "2023-07-04T22:36:02.000Z",
      date_published: "2023-07-04T22:36:02.000Z",
      meta_title: null,
      meta_description: null,
      sort: null,
      section_relation: ["3"],
      user_id: 341,
      rc_link: 105,
      city_link: 5,
      area_link: 32,
      product_price: 27000000,
      living_squares: 58.4,
      land_squares: null,
      map_coordinates: null,
      product_description:
        "Дизайнерский ремонт, без мебели\r\nВ ДКП сумма 6 млн\r\nВид на горы",
      status: "0",
      messages_calls: "0",
      product_placer: null,
      window_view: null,
      repairment: "0",
      cloud_links: null,
      comission: "Включена",
      comission_sum_terms: "по запросу",
      off_comission_value: null,
      mortgage: "0",
      stat_views: 19,
      published: 1,
      product_room_count: 1,
      sum_contract: "1",
      premium: "0",
      handed_over: 1,
      commercial_types: null,
      parking_types: null,
      object_squares: null,
      status_lands: null,
      house_types: null,
      house_floors: null,
      house_construction: null,
      flat_floors: 24,
      house_communication: null,
      date_banned: null,
      ban_note: null,
      edit_note: null,
      presentation: null,
      date_banned_to: null,
      date_paid: "2023-06-22T12:09:38.000Z",
      image: "/images/upload/2023-06-20/47a14d7164c5b58516236a123.jpeg",
      youtube_video_link: null,
      building_link: 52,
      pre_name: null,
      stat_views_preview: 832,
    },
    {
      id: 1811,
      name: "ЖК Курортный, 53.2 м², 2-комн.",
      slug: "zhk-kurortnii-53-2-m²-2-komn--1811",
      date_created: "2023-07-01T10:43:22.000Z",
      date_edited: "2023-07-01T10:49:02.000Z",
      date_published: "2023-07-01T10:49:02.000Z",
      meta_title: null,
      meta_description: null,
      sort: null,
      section_relation: ["3"],
      user_id: 449,
      rc_link: 36,
      city_link: 5,
      area_link: 66,
      product_price: 12130000,
      living_squares: 53.2,
      land_squares: null,
      map_coordinates: null,
      product_description: "8 корп, 3 этаж",
      status: "0",
      messages_calls: "0",
      product_placer: null,
      window_view: null,
      repairment: "1",
      cloud_links: null,
      comission: "Включена",
      comission_sum_terms: "по запросу",
      off_comission_value: null,
      mortgage: "0",
      stat_views: 6,
      published: 1,
      product_room_count: 1,
      sum_contract: "1",
      premium: "0",
      handed_over: 1,
      commercial_types: null,
      parking_types: null,
      object_squares: null,
      status_lands: null,
      house_types: null,
      house_floors: null,
      house_construction: null,
      flat_floors: null,
      house_communication: null,
      date_banned: null,
      ban_note: null,
      edit_note: null,
      presentation: null,
      date_banned_to: null,
      date_paid: null,
      image: "/images/upload/2023-07-01/018531d454471fc492e665551.128.jpeg",
      youtube_video_link: null,
      building_link: 60,
      pre_name: null,
      stat_views_preview: 0,
    },
  ],
  email_confirmed: false,
  phone_confirmed: false,
  email_confirmation: "7dd843b7b4f0ae6aadbed92384d8f38201aae9df71bbae182a",
  user_avatar: "/images/upload/2023-06-05/ce01ad6953d90ea12d4c9cf01.png",
  user_agency: "Хоук",
  default_city: {
    name: "Сочи",
    id: 5,
    slug: "sochi-5",
    in_name: "Сочи",
    date_created: "2022-12-27T10:16:12.000Z",
    date_edited: null,
  },
  professional_confirmation: "FLATE.PRO - ресурс только для агентов. ",
  sef_code: "andrey",
  additional_phones: ["+7 (937) 312-31-23"],
  product_count: null,
  properties: {},
};

const initialState = {
  value: {},
};

export const userLogin = createSlice({
  name: "userLogin",
  initialState,
  reducers: {
    getLogin: (state) => {
      state.value ? state.value : false;
    },
    setLogedIn: (state, action) => {
      state.value = action.payload.id ? action.payload : false;
    },
    setLogedOut: (state) => {
      state.value = false;
    },
  },
});

// Action creators are generated for each case reducer function
export const { getLogin, setLogedIn, setLogedOut, setTest } = userLogin.actions;

export default userLogin.reducer;
